# Site settings
title: Vesterheim Gold Medalist Portfolio
email: info@vesterheim.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://goldmedalist.vesterheim.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

exclude:
  - artists.rb
  - discipline.rb
  - states.rb
  - collections.txt
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - package.json
  - Connections
  - node_modules

paginate: 2

# Build settings
markdown: kramdown
permalink: pretty

collections:
  artists:
    output: true
    permalink: "artists/:path/"

# Markdown Processors
kramdown:
#  input:         kramdown
#  hard_wrap:     true
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  enable_coderay:   false

defaults:
  - scope:
      path: ""
      type: artists
    values:
      subtitle: Gold Medalist
      ancestors:
        - /artists/
        - /
        - //vesterheim.org/

picture:
  source: assets/images
  output: assets/images  
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5, 2]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 64em)"
        width: 746
      source_med1:
        media: "(min-width: 59em) and (max-width: 63.9375em)"
        width: 706
      source_med2:
        media: "(min-width: 55em) and (max-width: 58.9375em)"
        width: 628
      source_med3:
        media: "(min-width: 50em) and (max-width: 54.9375em)"
        width: 560
      source_med4:
        media: "(min-width: 42em) and (max-width: 49.9375em)"
        width: 486
      source_med5:
        media: "(min-width: 40em) and (max-width: 41.9375em)"
        width: 416
      source_med6:
        media: "(min-width: 38em) and (max-width: 39.9375em)"
        width: 628
      source_med7:
        media: "(min-width: 33em) and (max-width: 37.9375em)"
        width: 560
      source_med8:
        media: "(min-width: 28em) and (max-width: 32.9375em)"
        width: 486
      source_med9:
        media: "(min-width: 21em) and (max-width: 27.9375em)"
        width: 416
      source_default:
        width: 320      
    # Half width pictures such as tiles
    half:
      ppi: [1, 1.5, 2]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_med:
        media: "(min-width: 24.625em)"
        width: 368
      source_default:
        width: 184
    # Golden width pictures
    golden:
      ppi: [1, 1.5, 2]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_med:
        media: "(min-width: 54em)"
        width: 384
      source_med1:
        media: "(min-width: 40em) and (max-width: 53.9375em)"
        width: 384
      source_med2:
        media: "(min-width: 30em) and (max-width: 39.9375em)"
        width: 221
      source_med3:
        media: "(min-width: 25em) and (max-width: 29.9375em)"
        width: 464
      source_med4:
        media: "(min-width: 21em) and (max-width: 24.9375em)"
        width: 384
      source_default:
        width: 320    
    # Golden width pictures
    goldmedal:
      ppi: [1, 1.5, 2]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_med:
        media: "(min-width: 54em)"
        height: 175
        width: 384
      source_med1:
        media: "(min-width: 40em) and (max-width: 53.9375em)"
        height: 175
        width: 384
      source_med2:
        media: "(min-width: 30em) and (max-width: 39.9375em)"
        height: 101
        width: 221
      source_med3:
        media: "(min-width: 25em) and (max-width: 29.9375em)"
        height: 212
        width: 464
      source_med4:
        media: "(min-width: 21em) and (max-width: 24.9375em)"
        height: 175
        width: 384
      source_default:
        height: 146
        width: 320            
    # Fourth width pictures
    fourth:
      ppi: [1, 1.5, 2]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_med:
        media: "(min-width: 53em)"
        width: 154
      source_med1:
        media: "(min-width: 40em) and (max-width: 52.9375em)"
        width: 112
      source_med2:
        media: "(min-width: 30em) and (max-width: 39.9375em)"
        width: 142
      source_med3:
        media: "(min-width: 21em) and (max-width: 29.9375em)"
        width: 222
      source_default:
        width: 154 
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 600
        height: 400
      source_default:
        width: 250
        height: 250
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    full:
      source_default:
        width: 2000       